### ISSUE TITLE
Gets stuck

### ISSUE THREAD

**Issue by DealsBeam** [Smart123s/ItchClaim#5]
Script gets stuck at this: https://i.imgur.com/8hZMhAq.png / https://i.imgur.com/NfDwTds.png

Game: https://openchanter.itch.io/cosmic-conflict

**Comment by Smart123s** [comment]
Hi. I can see that you are using an extension alongside my site. My site's only job is to provide links to free games. Everything else is handled by your extension, so the problem probably lies there. Which extension are you using, if I may ask?

**Comment by DealsBeam** [comment]
The game listed on ItchClaim says it's free but it's paid

I'm using https://github.com/HCLonely/user.js script on TamperMonkey

**Comment by Smart123s** [comment]
The game had one sale in the database, that ended on Mon Oct 23 2023
04:00:00 GMT+0000 (1698033600 unix seconds). Tho if you open the sale page
https://itch.io/s/105131/free-games, it says that "This sale ended Last
Thursday at 6:00 AM.".  Most likely, the developer has changed the sale to
make it end earlier. Itch claim checks sales only once, and doesn't recheck
after, so it's possible that expired sales are listed on the site. It's
also worth noting, that the site gets updated only every six hours, so
sales expiring between the 6 hour window are also visible on the site until
the next update.

As to why the script got stuck on an expired sale: I have absolutely no
clue, but that issue is related to the script, so you should also notify
it's developer via a GitHub issue.
